# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Run tests and publish

on:
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-tests-node-12:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install depencencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Enable docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest
      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to docker with buildx as latest
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --push \
            -t ${{ secrets.DOCKERHUB_REGISTRYNAME }}/${{ env.IMAGE_NAME }}:latest
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILD_VERSION=${{ steps.semantic.outputs.new_release_version }} \
            --build-arg VSC_REF=$(echo ${GITHUB_SHA} | cut -c1-8) \
            .
